ROOM_TYPE_PRIVATE = 200
ROOM_TYPE_PUBLIC = 100
GET_ALL_MESSAGES = -1
DEFAULT_ROOM_LIST_NAME = "default_room_list"
DEFAULT_USER_LIST_NAME = "default_user_list"
DEFAULT_PUBLIC_ROOM = "default_public_name"